version: '3'
services:
  # Angular Landing Page
  angular-17-jwt-auth:
    image: uportal/angular-17-jwt-auth-starter-standalone:latest
    container_name: angular-17-jwt-auth
    ports:
      - 4100:80
    # uncomment lines for build if the build of the image has to be performed
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    environment:
      API_URL: http://localhost:8080/api/test/
      LOGIN_URL: http://localhost:8080/api/auth/
      SIGNUP_URL: http://localhost:8080/api/auth/
